### ISSUE TITLE
Rack deletes items

### ISSUE THREAD

**Issue by Danklor** [Globox1997/FleshZ#1]
When attempting to take items off the rack with a full inventory the items are voided.  I would expect the items to drop to the ground instead.

MC 1.16.5
Fabric loader 0.11.1 API 0.30.3+1.16
FleshZ 1.2.2 (Nov 2020 update)
Other mods also loaded, but I don't think they are a factor

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/FleshZ/commit/05dace0e5d244d301daa522039483a03b84235bf](https://github.com/Globox1997/FleshZ/commit/05dace0e5d244d301daa522039483a03b84235bf)
