### ISSUE TITLE
Mistake in meadow compact

### ISSUE THREAD

**Issue by benio1394** [Globox1997/FleshZ#13]
### Minecraft Version

1.20.x

### Mod Loader Version

0.16.0

### Mod Version

1.5.1

### Describe the Issue

There is a mistake in resourcepack compact - water buffalo from Let's do Meadow should drop meadow: raw_buffalo_meat instead of minecraft:beef 

https://github.com/Globox1997/FleshZ/blob/1.21/src/main/resources/resourcepacks/meadow_compat/data/meadow/loot_table/entities/water_buffalo.json

### latest.log

-

### Do you use any other mods except the required ones?

Let's do Meadow

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/FleshZ/commit/13209fe6704efef011d98db7ab50468acf602d3d](https://github.com/Globox1997/FleshZ/commit/13209fe6704efef011d98db7ab50468acf602d3d)
