### ISSUE TITLE
Major trouble hanging anything on the drying rack [1.17]

### ISSUE THREAD

**Issue by Kailied** [Globox1997/FleshZ#2]
I'm using the newest release, and I have to right click many many times before even getting a chance that it gets hung on the rack. This applies to both rotten and prepared hide. It is extremely frustrating, I've barely been able to hang 10 or so leather in the span of 30 minutes. Mostly it won't even go on the rack, though it appears to do so for a tick, and sometimes it goes on but I'm clicking so fast because of how many clicks it takes, that I end up taking it off.

**Comment by chainsawpenguin** [comment]
Same issue, except I can't hang anything at all no matter how many times I click

**Comment by vZekii** [comment]
Same issue on a server using the mod, very annoying as this overrides all ways to get leather in the modpack

**Comment by Globox1997** [comment]
Investigated the problem, or at least I tried with no problem occurring.
Does this happen when FleshZ is only installed?

**Comment by CanINotUseTruth** [comment]
I recently created a mod that implements a drying rack just like you have in FleshZ and used some of the code to get my one working and I'm getting a similar problem. From my testing it seems that the onUse function fires twice per click when playing on a server which I assume the people that reported this issue above are cause the issue doesn't happen in singleplayer. Once you log in to a single player world however (per each time the game launches) it seems to rectify the issue when you are holding items but when your hand is empty the onUse function fires twice still not that that is a problem though cause an empty hand is just to remove an item and usually an item that is complete can't go back on. I made a small clip to maybe better show what I'm trying to explain. I haven't been able to figure out a fix yet either but two heads are better than one?

Video Link: https://youtu.be/OJkZK2yh4ZI

Edit: onUse fires twice on server and singleplayer (from testing it seems to be the server and client both attempting the onUse function). On Multiplayer without logging in to SP the server and client both fire the onUse 2 times (this is when the error occurs), then logging into a single player world the Client then the Server attempts onUse (works fine). After logging into a single player world back on multiplayer, it seperates the client and server correctly when calling onUse (fixes issue) each only fire once.

**Comment by Globox1997** [comment]
Okay I found the bug and it happens as @CanINotUseTruth said:
If you directly join a server, you won't be able to use the rack (cause of double method execution)
You will need to join a sp world and join the server 

@CanINotUseTruth instead of just ripping the code, you can jij the mod or use cursemaven to implement it into your mod :)
(that is how it is intended for) let me know if you have any questions

**Comment by Globox1997** [comment]
I wonder if this happened in version 1.16.5 too, if someone can test it on a server would be highly appreciated

**Comment by Globox1997** [comment]
Should be fixed with the latest update
