### ISSUE TITLE
FleshZ gets overwrited by Decorative Blocks

### ISSUE THREAD

**Issue by TheButterbrotMan** [Globox1997/FleshZ#4]
Gets overwriten by https://www.curseforge.com/minecraft/mc-mods/decorative-blocks

Wood Rack is getting unusable

**Comment by Danklor** [comment]
I'm working with a pack that contains both these mods, but the FleshZ rack is working as intended (unless the chunk containing the rack unloads during processing.)

Maybe I'm not doing all the steps needed. How did you make the problem appear? Was it in singleplayer or on a server?
