### ISSUE TITLE
Rack deletes items if chunk containing rack unloads during processing

### ISSUE THREAD

**Issue by Danklor** [Globox1997/FleshZ#6]
If a rack containing rotten flesh or prepared hide becomes unloaded then on return to the area or relog the item will show up at first, but when drying is complete it will be deleted rather than becoming the intended product.
The rack works normally if the rack's chunk is loaded for the entire drying process.

MC 1.18.1 + Fabric 0.12.12 & API 0.46.1
FleshZ 1.4.4
Many other mods, but I don't think this is a conflict.
Tested in singleplayer.

**Comment by SkrubbySkrubInAShrub** [comment]
can confirm same happens on 1.18.2

**Comment by Globox1997** [comment]
Thanks for reporting, for some reason I've overseen this issue, fixed with [https://github.com/Globox1997/FleshZ/commit/2bcc317a9ec561164840a01e509d8aa93f0e3dcb](https://github.com/Globox1997/FleshZ/commit/2bcc317a9ec561164840a01e509d8aa93f0e3dcb)
