### ISSUE TITLE
I would want to request compatiblity for other mods Leather/Hide! :)

### ISSUE THREAD

**Issue by TheButterbrotMan** [Globox1997/FleshZ#7]
1. [Rabbit Hide](https://minecraft.fandom.com/wiki/Rabbit_Hide)
2. [Rhino Leather](https://www.curseforge.com/minecraft/mc-mods/adventurez)
3. [Iguana Hide](https://www.curseforge.com/minecraft/mc-mods/adventurez)
4. [Mammoth Fur](https://www.curseforge.com/minecraft/mc-mods/adventurez)

**Comment by Globox1997** [comment]
This should be done via a datapack since those mods don't depend on each other and it would lead to non existing recipes in the client/server log when only one mod is loaded

**Comment by TheButterbrotMan** [comment]
This is possible, without errors in log, via a ",if X enable datapack".

Checkout this mod, we did it there.

https://www.curseforge.com/minecraft/mc-mods/just-enough-hammers

**Comment by Globox1997** [comment]
Thanks for the info :)
Added compat with [https://github.com/Globox1997/AdventureZ/commit/8014780a637ea89b4d311aeea68064b6aa7139e6](https://github.com/Globox1997/AdventureZ/commit/8014780a637ea89b4d311aeea68064b6aa7139e6)
