### ISSUE TITLE
Any form of automation causes Wood Rack to delete Cured Hide

### ISSUE THREAD

**Issue by wiilover22** [Globox1997/FleshZ#8]
Problem is as title states: If you attempt to automate the placement of Cured Hide onto a Wood Rack (with either a Dropper, or a "Basic Inventory Hopper" from "Tom's Simple Storage Mod"), the Cured Hide appears on the Wood Rack for a moment, then gets deleted.

This makes any form of automation impossible currently.

**Comment by Globox1997** [comment]
Thanks for the report, fixed hopper interaction with [https://github.com/Globox1997/FleshZ/commit/f092f02050e80c29563def44aa9cc46b0e559e10](https://github.com/Globox1997/FleshZ/commit/f092f02050e80c29563def44aa9cc46b0e559e10)
